image: hipay/gitlab-ci-base:jessie

variables:
  MAGENTO_URL: http://127.0.0.1/
  MAGENTO_URL_SECURE: https://127.0.0.1/
  PORT_WEB: 80


stages:
 - build
 - analysis
 - deploy
 - sync

casperjs-part1:
  stage: build
  before_script:
    - sed -i -e "s|{MAGENTO_URL\}|$MAGENTO_URL|" ./bin/conf/stage/mage.env.sample
    - sed -i -e "s|{MAGENTO_URL_SECURE\}|$MAGENTO_URL_SECURE|" ./bin/conf/stage/mage.env.sample
    - sed -i -e "s/{PORT_WEB\}/$PORT_WEB/" ./bin/conf/stage/mage.env.sample
    - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_TEST/" ./bin/conf/stage/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_TEST/" ./bin/conf/stage/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_TEST/" ./bin/conf/stage/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_TEST/" ./bin/conf/stage/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/conf/stage/hipay.env.sample
    - sed -i -e "s/{ACTIVE_METHODS\}/$ACTIVE_METHODS/" ./bin/conf/stage/hipay.env.sample
    - sed -i -e "s/{GITHUB_API_TOKEN\}/$GITHUB_TOKEN/" ./bin/conf/stage/auth.env.sample
    - sed -i -e "s/{GITLAB_API_TOKEN\}/$GITLAB_API_TOKEN/" ./bin/conf/stage/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PUBLIC_KEY\}/$MAGE_ACCOUNT_PUBLIC_KEY/" ./bin/conf/stage/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PRIVATE_KEY\}/$MAGE_ACCOUNT_PRIVATE_KEY/" ./bin/conf/stage/auth.env.sample
    - sed -i "s/$(echo "{BRANCH}" | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $CI_COMMIT_REF_NAME | sed -e 's/[\/&]/\\&/g')/g" ./bin/conf/stage/module.env.sample
    - docker-compose -f docker-compose.yml -f docker-compose.stage.yml build --no-cache
    - docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d
    - sleep 600
    - docker-compose -f docker-compose.yml -f docker-compose.stage.yml logs
    - curl --retry 10 --retry-delay 20 -v http://magento2
  script:
    - docker exec "hipay-mg2-"$CI_JOB_ID phpunit -c /var/www/html/magento2/vendor/hipay/hipay-fullservice-sdk-magento2/tests/unit/phpunit.xml.dist
    - sh bin/tests/casper_run_circle.sh http://magento2
  allow_failure: false
  artifacts:
    paths:
    - bin/tests/errors
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose.stage.yml stop
    - docker-compose -f docker-compose.yml -f docker-compose.stage.yml rm -fv

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://172.17.0.1:19000
    SONAR_ANALYSIS_MODE: preview
    SONAR_TOKEN: $SONAR_LOGIN
  script:
  - /usr/bin/sonar-scanner-run.sh -X

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://172.17.0.1:19000
    SONAR_ANALYSIS_MODE: "publish"
    SONAR_TOKEN: $SONAR_LOGIN
  script:
  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh

deploy:
 stage: deploy
 script:
  - docker exec deploy.hipay-pos-platform.com /deploy/deploy_project.sh  $CI_PROJECT_NAME $CI_COMMIT_REF_NAME gitlab

sync:
  stage: sync
  script:
  - git clone --mirror https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.hipay.org/pi-ecommerce/hipay-fullservice-sdk-magento2.git
  - cd hipay-fullservice-sdk-magento2.git
  - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/hipay/hipay-fullservice-sdk-magento2.git
  allow_failure: true
